### ISSUE TITLE
Functions in cl-ana.generic-math can enter infinite loops with sequences with nils

### ISSUE THREAD

**Issue by kat-co** [ghollisjr/cl-ana#29] opened 2019-05-13 17:25 UTC
Here is the smallest reproducible test case: `(cl-ana.generic-math:add 1 nil)`. This will never return. My guess is that cl-ana is swallowing a condition somewhere in a loop.

A higher order issue may be how this edge-cases is even entered. I was calling `cl-ana.statistics:mean` passing a vector with `nil`s interspersed throughout.

**Comment by ghollisjr** [comment] 2019-05-14 05:54
Ah this is a very dusty corner of cl-ana.  I noticed this a long time ago and forgot to fix it.  The problem is the implementation of the arithmetic operations in the cl-ana.tensor library.  NIL is not expected but is also not handled properly.  I think the right thing to do here is to make sure that generic-math functions return NIL when one of their arguments is NIL, so I'll add this to the automatic method definition in cl-ana.tensor.

**Comment by ghollisjr** [comment] 2019-05-14 06:00
Fix committed.

**Closed by ghollisjr** 2019-05-14 06:00 UTC
